import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "XBP Global Interview",
  description: "Generated by XBP Global AI Interview",
};

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
        {children}
           <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
